"use client";

import { useState } from "react";
import Link from "next/link";
import type { RoiMetrics } from "@/lib/types";

type Props = {
  listingId: string;
  productName: string;
  totalBid: number;
  clickCount: number;
  initialRoi?: RoiMetrics;
};

type AdBenchmark = {
  name: string;
  platform: string;
  cpc: number;
  icon: string;
};

const BENCHMARKS: AdBenchmark[] = [
  { name: "Google Search Ads (B2B SaaS)", platform: "Google Ads", cpc: 2.50, icon: "🔍" },
  { name: "Twitter / 𝕏 Promoted Ads", platform: "X Ads", cpc: 1.50, icon: "𝕏" },
  { name: "LinkedIn Sponsored Content", platform: "LinkedIn", cpc: 5.50, icon: "💼" },
];

export default function RoiCalculatorCard({
  listingId,
  productName,
  totalBid,
  clickCount,
  initialRoi,
}: Props) {
  const [selectedBenchmark, setSelectedBenchmark] = useState<AdBenchmark>(BENCHMARKS[0]);
  const [simulatedExtraBid, setSimulatedExtraBid] = useState<number>(0);

  // Current Metrics
  const effectiveCpc =
    clickCount > 0 && totalBid > 0 ? Number((totalBid / clickCount).toFixed(2)) : 0;
  const benchmarkCpc = selectedBenchmark.cpc;
  const savingsPct =
    effectiveCpc > 0 && effectiveCpc < benchmarkCpc
      ? Math.round((1 - effectiveCpc / benchmarkCpc) * 100)
      : 0;
  const estimatedMarketValue = Number((clickCount * benchmarkCpc).toFixed(2));
  const roiMultiple =
    totalBid > 0 ? Number((estimatedMarketValue / totalBid).toFixed(1)) : 0;

  // Simulated Metrics
  const simulatedTotalBid = totalBid + simulatedExtraBid;
  const simulatedClicks =
    clickCount > 0 && totalBid > 0
      ? Math.round(clickCount * (1 + (simulatedExtraBid / totalBid) * 1.15))
      : simulatedExtraBid > 0
      ? Math.round(simulatedExtraBid / 0.25)
      : 0;
  const simulatedCpc =
    simulatedClicks > 0 ? Number((simulatedTotalBid / simulatedClicks).toFixed(2)) : effectiveCpc;
  const simulatedMarketValue = Number((simulatedClicks * benchmarkCpc).toFixed(2));
  const simulatedSavingsPct =
    simulatedCpc > 0 && simulatedCpc < benchmarkCpc
      ? Math.round((1 - simulatedCpc / benchmarkCpc) * 100)
      : 0;

  return (
    <div className="rounded-xl bg-card border border-border p-5 shadow-xs transition-all">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-2 pb-4 border-b border-border/60">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-lg bg-emerald-500/10 text-emerald-400 text-sm">
              📈
            </span>
            <h3 className="text-base font-bold text-foreground">
              Private Analytics &amp; ROI Calculator
            </h3>
          </div>
          <p className="text-xs text-muted-foreground mt-0.5">
            Real business value and cost efficiency generated by your GoClaim placement.
          </p>
        </div>

        {/* Benchmark Picker */}
        <div className="flex items-center gap-1.5 bg-muted/60 p-1 rounded-lg border border-border/50 text-xs">
          <span className="text-[11px] text-muted-foreground px-1.5 font-medium">Compare:</span>
          {BENCHMARKS.map((b) => (
            <button
              key={b.platform}
              type="button"
              onClick={() => setSelectedBenchmark(b)}
              className={`px-2 py-1 rounded-md text-xs font-semibold transition-all cursor-pointer ${
                selectedBenchmark.platform === b.platform
                  ? "bg-primary text-primary-foreground shadow-2xs"
                  : "text-muted-foreground hover:text-foreground hover:bg-muted"
              }`}
            >
              <span>{b.icon}</span> <span className="hidden sm:inline">{b.platform}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Prominent Callout Quote Badge */}
      <div className="mt-4 p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/30 text-emerald-100 relative overflow-hidden">
        <div className="flex items-start gap-3">
          <div className="p-2 rounded-lg bg-emerald-500/20 text-emerald-400 text-lg shrink-0">
            ⚡
          </div>
          <div className="min-w-0 flex-1">
            <p className="text-xs font-bold uppercase tracking-wider text-emerald-400">
              Efficiency Statement
            </p>
            <p className="text-sm sm:text-base font-semibold text-emerald-200 mt-1 leading-snug">
              {clickCount > 0 && totalBid > 0 ? (
                <>
                  You bid <strong className="text-white">${totalBid.toLocaleString()}</strong> and
                  received <strong className="text-white">{clickCount.toLocaleString()} clicks</strong>.
                  Your effective CPC is{" "}
                  <strong className="text-white">${effectiveCpc.toFixed(2)}</strong>{" "}
                  <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-emerald-500/30 text-emerald-300 border border-emerald-500/40">
                    {savingsPct}% cheaper than {selectedBenchmark.platform}
                  </span>.
                </>
              ) : (
                <>
                  Your listing is live on GoClaim. Every click you receive generates high-intent
                  developer/founder traffic at a fraction of traditional ad costs.
                </>
              )}
            </p>
          </div>
        </div>
      </div>

      {/* ROI Metrics Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4">
        {/* Metric 1: Effective CPC */}
        <div className="rounded-xl bg-muted/40 border border-border/70 p-3.5 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
                Effective CPC
              </span>
              <span className="text-xs">🎯</span>
            </div>
            <p className="text-2xl font-extrabold text-foreground tabular-nums mt-1">
              {effectiveCpc > 0 ? `$${effectiveCpc.toFixed(2)}` : "—"}
            </p>
          </div>
          <p className="text-[11px] text-muted-foreground mt-2 pt-2 border-t border-border/40 flex items-center justify-between">
            <span>vs. {selectedBenchmark.platform}:</span>
            <span className="line-through opacity-75 tabular-nums">${benchmarkCpc.toFixed(2)}</span>
          </p>
        </div>

        {/* Metric 2: Ad Spend Savings */}
        <div className="rounded-xl bg-muted/40 border border-border/70 p-3.5 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
                Ad Cost Savings
              </span>
              <span className="text-xs text-emerald-400 font-bold">
                {savingsPct > 0 ? `-${savingsPct}%` : ""}
              </span>
            </div>
            <p className="text-2xl font-extrabold text-emerald-400 tabular-nums mt-1">
              {savingsPct > 0 ? `${savingsPct}%` : "—"}
            </p>
          </div>
          <p className="text-[11px] text-muted-foreground mt-2 pt-2 border-t border-border/40">
            cheaper than {selectedBenchmark.platform}
          </p>
        </div>

        {/* Metric 3: Estimated Market Value */}
        <div className="rounded-xl bg-muted/40 border border-border/70 p-3.5 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
                Market Value
              </span>
              <span className="text-xs">💎</span>
            </div>
            <p className="text-2xl font-extrabold text-foreground tabular-nums mt-1">
              ${estimatedMarketValue.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}
            </p>
          </div>
          <p className="text-[11px] text-muted-foreground mt-2 pt-2 border-t border-border/40">
            value if bought on {selectedBenchmark.platform}
          </p>
        </div>

        {/* Metric 4: ROAS Multiplier */}
        <div className="rounded-xl bg-muted/40 border border-border/70 p-3.5 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">
                ROAS Multiplier
              </span>
              <span className="text-xs">🚀</span>
            </div>
            <p className="text-2xl font-extrabold text-primary tabular-nums mt-1">
              {roiMultiple > 0 ? `${roiMultiple}x` : "—"}
            </p>
          </div>
          <p className="text-[11px] text-muted-foreground mt-2 pt-2 border-t border-border/40">
            return on ${totalBid.toLocaleString()} bid
          </p>
        </div>
      </div>

      {/* Interactive "What-If" Bid & Traffic Simulator */}
      <div className="mt-5 p-4 rounded-xl bg-muted/30 border border-border/60">
        <div className="flex items-center justify-between flex-wrap gap-2 mb-3">
          <div className="flex items-center gap-2">
            <span className="text-xs">🧪</span>
            <span className="text-xs font-bold text-foreground">
              Interactive ROI &amp; Traffic Simulator
            </span>
          </div>
          <span className="text-[11px] text-muted-foreground">
            Preview traffic growth if you raise your bid
          </span>
        </div>

        <div className="flex items-center gap-2 flex-wrap mb-3">
          <span className="text-xs text-muted-foreground">Simulate Bid Increase:</span>
          {[10, 25, 50, 100].map((amt) => (
            <button
              key={amt}
              type="button"
              onClick={() => setSimulatedExtraBid(amt === simulatedExtraBid ? 0 : amt)}
              className={`px-2.5 py-1 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                simulatedExtraBid === amt
                  ? "bg-primary text-primary-foreground shadow-2xs"
                  : "bg-muted hover:bg-muted/80 text-foreground border border-border"
              }`}
            >
              +${amt}
            </button>
          ))}
          {simulatedExtraBid > 0 && (
            <button
              type="button"
              onClick={() => setSimulatedExtraBid(0)}
              className="text-xs text-muted-foreground hover:text-foreground underline ml-1 cursor-pointer"
            >
              Reset
            </button>
          )}
        </div>

        {simulatedExtraBid > 0 ? (
          <div className="p-3 rounded-lg bg-card border border-primary/30 flex items-center justify-between flex-wrap gap-3">
            <div className="text-xs space-y-0.5">
              <p className="font-semibold text-foreground">
                With a <strong className="text-primary">+${simulatedExtraBid}</strong> increase (total ${simulatedTotalBid}):
              </p>
              <p className="text-muted-foreground text-[11px]">
                Projected ~<strong className="text-emerald-400">{simulatedClicks} clicks</strong> (~+
                {simulatedClicks - clickCount} new visitors) at effective CPC of{" "}
                <strong className="text-foreground">${simulatedCpc.toFixed(2)}</strong> ({simulatedSavingsPct}% cheaper than {selectedBenchmark.platform}).
              </p>
            </div>
            <Link
              href={`/?raise=${listingId}`}
              className="px-3.5 py-1.5 rounded-lg bg-primary hover:bg-primary/90 text-primary-foreground text-xs font-bold transition-all shadow-xs shrink-0"
            >
              Raise Bid +${simulatedExtraBid} ↗
            </Link>
          </div>
        ) : (
          <p className="text-[11px] text-muted-foreground italic">
            Click any amount above (+ $10, + $25, + $50, + $100) to project clicks and CPC efficiency at higher bidding tiers.
          </p>
        )}
      </div>
    </div>
  );
}
